import React, { useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Grid, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { Add, LockOutlined, SendOutlined, ShieldOutlined } from '@mui/icons-material';
import { useAuthStore } from '../../store';
import { nexusApi, PortalIdentity } from '../../services/nexusApi';

const institutionId = 'inst-nashik-hospital';
export default function InstitutionPortal(): React.ReactElement {
  const { user } = useAuthStore(); const [notice, setNotice] = useState<string>(); const [submitting, setSubmitting] = useState(false);
  const identity = useMemo<PortalIdentity>(() => ({ role: 'institution', subject: user?.user_id || 'institution-demo', jurisdictions: user?.jurisdictions || ['district:nashik'], institutionId }), [user]);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setSubmitting(true); setNotice(undefined); try { await nexusApi.submitInvoice(institutionId, { jurisdiction: data.get('jurisdiction'), tender_reference: data.get('reference'), category: data.get('category'), amount: Number(data.get('amount')), line_items: [{ description: data.get('description'), quantity: 1 }], gst: data.get('gst') }, identity); event.currentTarget.reset(); setNotice('Invoice received. Sensitive identifiers were tokenized before storage.'); } catch { setNotice('Unable to submit the invoice. Check your institution scope and try again.'); } finally { setSubmitting(false); } };
  return <Box><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} spacing={2} mb={3}><Box><Typography variant="overline" color="secondary">INSTITUTION PORTAL / SUBMIT</Typography><Typography variant="h4" fontWeight={700}>Submit an invoice</Typography><Typography variant="body2" color="text.secondary">Structured data only — documents remain opaque evidence and never enter the AI context.</Typography></Box><Chip icon={<ShieldOutlined />} label="Institution-scoped access" sx={{ bgcolor: '#DDF4E6', color: '#1E6B4A', fontWeight: 700 }} /></Stack>
    <Grid container spacing={3}><Grid item xs={12} md={8}><Card sx={{ borderRadius: 4 }}><CardContent sx={{ p: 3 }}><Stack direction="row" spacing={1} mb={3}>{['Tender info','Vendor details','Line items','Amount','Documents'].map((step, index) => <Chip key={step} label={`${index + 1}. ${step}`} color={index === 0 ? 'primary' : 'default'} variant={index === 0 ? 'filled' : 'outlined'} />)}</Stack>{notice && <Alert severity={notice.startsWith('Invoice received') ? 'success' : 'error'} sx={{ mb: 2 }}>{notice}</Alert>}<Box component="form" onSubmit={submit}><Grid container spacing={2}><Grid item xs={12} sm={6}><TextField fullWidth required name="reference" label="Reference number" placeholder="PO-2026-118" /></Grid><Grid item xs={12} sm={6}><TextField fullWidth required select name="jurisdiction" label="Jurisdiction" defaultValue={identity.jurisdictions[0]}>{identity.jurisdictions.map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField fullWidth required name="category" label="Procurement category" defaultValue="Medical supplies" /></Grid><Grid item xs={12} sm={6}><TextField fullWidth required name="amount" type="number" label="Invoice amount" inputProps={{ min: 1 }} /></Grid><Grid item xs={12}><TextField fullWidth required multiline minRows={3} name="description" label="Line item description" /></Grid><Grid item xs={12}><TextField fullWidth name="gst" label="Vendor GST (tokenized at ingestion)" helperText="Stored as a token; full value is never returned to this portal." /></Grid></Grid><Stack direction="row" justifyContent="flex-end" mt={3}><Button type="submit" variant="contained" disabled={submitting} startIcon={<SendOutlined />}>{submitting ? 'Submitting…' : 'Submit invoice'}</Button></Stack></Box></CardContent></Card></Grid><Grid item xs={12} md={4}><Stack spacing={2}><Card sx={{ bgcolor: '#FFF9EC', borderRadius: 4 }}><CardContent><Typography variant="overline" color="#8A5A15">PRIVACY CONTROL</Typography><Stack direction="row" spacing={1} alignItems="center"><LockOutlined color="warning"/><Typography fontWeight={700}>Maker-checker unmasking</Typography></Stack><Typography variant="body2" color="text.secondary" mt={1}>Auditors can request access, but your authorized checker must approve or deny it with a recorded reason.</Typography></CardContent></Card><Card sx={{ borderRadius: 4 }}><CardContent><Typography fontWeight={700}>Digital Twin Health</Typography><Typography variant="h3" color="#1E6B4A" fontWeight={700}>86</Typography><Typography variant="body2" color="text.secondary">Healthy · updated today</Typography></CardContent></Card></Stack></Grid></Grid></Box>;
}
