import React, { useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Grid,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Paper,
  Divider,
} from '@mui/material';
import {
  Description as EvidenceIcon,
  Verified as VerifiedIcon,
  Fingerprint as HashIcon,
} from '@mui/icons-material';
import { EvidenceItem } from '../../../types';

interface EvidenceViewerProps {
  evidence: EvidenceItem[];
}

export const EvidenceViewer: React.FC<EvidenceViewerProps> = ({ evidence }) => {
  const [selectedEvidence, setSelectedEvidence] = useState<EvidenceItem | null>(null);

  return (
    <Card sx={{ mb: 3 }}>
      <CardContent>
        <Box display="flex" alignItems="center" gap={1} mb={2}>
          <EvidenceIcon color="primary" />
          <Typography variant="h6" fontWeight={700}>
            Cryptographic Evidence Bundle ({evidence?.length || 0} Artifacts)
          </Typography>
        </Box>

        <Grid container spacing={2}>
          {evidence?.map((item) => (
            <Grid item xs={12} sm={6} md={3} key={item.evidence_id}>
              <Paper
                elevation={0}
                sx={{
                  p: 2,
                  border: '1px solid',
                  borderColor: 'divider',
                  borderRadius: 2,
                  cursor: 'pointer',
                  transition: 'all 0.2s',
                  '&:hover': {
                    borderColor: 'primary.main',
                    boxShadow: '0 4px 12px rgba(0,0,0,0.05)',
                  },
                }}
                onClick={() => setSelectedEvidence(item)}
              >
                <Box display="flex" justifyContent="space-between" alignItems="center" mb={1}>
                  <Chip
                    label={item.evidence_id.toUpperCase()}
                    size="small"
                    color="primary"
                    variant="outlined"
                    sx={{ fontWeight: 700 }}
                  />
                  <Chip
                    label={`${(item.confidence * 100).toFixed(0)}% Conf`}
                    size="small"
                    color="success"
                  />
                </Box>
                <Typography variant="subtitle2" fontWeight={600} noWrap>
                  {item.evidence_type.replace(/_/g, ' ')}
                </Typography>
                <Typography
                  variant="caption"
                  color="text.secondary"
                  sx={{
                    display: '-webkit-box',
                    WebkitLineClamp: 2,
                    WebkitBoxOrient: 'vertical',
                    overflow: 'hidden',
                    mt: 0.5,
                  }}
                >
                  {item.description}
                </Typography>
              </Paper>
            </Grid>
          ))}
        </Grid>
      </CardContent>

      {/* Evidence Detail Modal */}
      <Dialog
        open={Boolean(selectedEvidence)}
        onClose={() => setSelectedEvidence(null)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>
          <Box display="flex" alignItems="center" gap={1}>
            <VerifiedIcon color="success" />
            <Typography variant="h6">
              Evidence Detail: {selectedEvidence?.evidence_id.toUpperCase()}
            </Typography>
          </Box>
        </DialogTitle>
        <DialogContent dividers>
          {selectedEvidence && (
            <Box display="flex" flexDirection="column" gap={2}>
              <Box>
                <Typography variant="caption" color="text.secondary">Evidence Type</Typography>
                <Typography variant="subtitle2" fontWeight={700}>
                  {selectedEvidence.evidence_type.replace(/_/g, ' ')}
                </Typography>
              </Box>

              <Box>
                <Typography variant="caption" color="text.secondary">Description & Finding</Typography>
                <Typography variant="body2">{selectedEvidence.description}</Typography>
              </Box>

              <Divider />

              <Box>
                <Typography variant="caption" color="text.secondary">Extraction Source & Confidence</Typography>
                <Typography variant="body2">
                  Generated by <strong>{selectedEvidence.source}</strong> (Confidence: {(selectedEvidence.confidence * 100).toFixed(1)}%)
                </Typography>
              </Box>

              <Box>
                <Typography variant="caption" color="text.secondary">Structured Evidence Metadata</Typography>
                <Paper sx={{ p: 1.5, bgcolor: 'action.hover', mt: 0.5 }}>
                  <Typography
                    variant="caption"
                    component="pre"
                    sx={{ fontFamily: 'monospace', whiteSpace: 'pre-wrap', m: 0 }}
                  >
                    {JSON.stringify(selectedEvidence.data, null, 2)}
                  </Typography>
                </Paper>
              </Box>

              <Box display="flex" alignItems="center" gap={1}>
                <HashIcon fontSize="small" color="action" />
                <Typography variant="caption" color="text.secondary" fontFamily="monospace">
                  Integrity Verified • SHA-256 Hash Chain Match
                </Typography>
              </Box>
            </Box>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setSelectedEvidence(null)}>Close</Button>
        </DialogActions>
      </Dialog>
    </Card>
  );
};

export default EvidenceViewer;
