import React from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  LinearProgress,
  Chip,
  Tooltip,
} from '@mui/material';
import { Signal } from '../../../types';

interface SignalBreakdownProps {
  signals: Signal[];
}

export const SignalBreakdown: React.FC<SignalBreakdownProps> = ({ signals }) => {
  const getSignalColor = (val: number): 'error' | 'warning' | 'success' => {
    if (val > 0.7) return 'error';
    if (val > 0.4) return 'warning';
    return 'success';
  };

  return (
    <Card sx={{ height: '100%' }}>
      <CardContent>
        <Typography variant="h6" fontWeight={700} gutterBottom>
          Multi-Detector Risk Signals ({signals?.length || 0})
        </Typography>
        <Typography variant="body2" color="text.secondary" mb={2}>
          Individual signal outputs generated by the ensemble detection pipelines.
        </Typography>

        <Box display="flex" flexDirection="column" gap={2}>
          {signals?.map((sig, idx) => {
            const pct = Math.round(sig.signal_value * 100);
            const color = getSignalColor(sig.signal_value);

            return (
              <Box key={idx} sx={{ p: 1.5, borderRadius: 1.5, bgcolor: 'action.hover' }}>
                <Box display="flex" justifyContent="space-between" alignItems="center" mb={1}>
                  <Box>
                    <Typography variant="subtitle2" fontWeight={700}>
                      {sig.detector_type.replace(/_/g, ' ')}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      Confidence: {(sig.confidence * 100).toFixed(0)}% • {sig.evidence_ids?.length || 0} linked evidence
                    </Typography>
                  </Box>
                  <Tooltip title={`Raw Detector Output: ${sig.signal_value.toFixed(4)}`}>
                    <Chip
                      label={`${pct}%`}
                      color={color}
                      size="small"
                      sx={{ fontWeight: 700 }}
                    />
                  </Tooltip>
                </Box>
                <LinearProgress
                  variant="determinate"
                  value={pct}
                  color={color}
                  sx={{ height: 8, borderRadius: 4 }}
                />
                {sig.metadata && Object.keys(sig.metadata).length > 0 && (
                  <Box mt={1} display="flex" flexWrap="wrap" gap={0.5}>
                    {Object.entries(sig.metadata).map(([k, v]) => (
                      <Chip
                        key={k}
                        label={`${k.replace(/_/g, ' ')}: ${String(v)}`}
                        size="small"
                        variant="outlined"
                        sx={{ fontSize: '0.65rem' }}
                      />
                    ))}
                  </Box>
                )}
              </Box>
            );
          })}
        </Box>
      </CardContent>
    </Card>
  );
};

export default SignalBreakdown;
